### ISSUE TITLE
Multi-GPU Support

### ISSUE THREAD

**Issue by yehorkhod** [LennartPurucker/finetune_tabpfn_v2#10]
Hi there!

I wanted to fine-tune the TabPFN model on my dataset, but I encountered GPU memory limitations.

- On my local machine, I could only fit 300 samples into train set.
- On an H100 machine, I managed 3000 samples.
- When I rented 6x 4090 GPUs, the model didn’t seem to utilize all of them, and I couldn’t increase the dataset size further.

### Question?
Is it possible to make this library utilize multiple GPUs for fine-tuning? If so, how should I configure it?

### Code I've used for tuning:
~~~py
fine_tune_tabpfn(
    X_train=X_train,  # shape: 3000x73
    y_train=y_train,  # shape: 3000
    X_val=X_val,  # shape: 8893x73
    y_val=y_val,  # shape: 3000

    # Finetuning parameters
    time_limit=TIME_LIMIT,
    finetuning_config={"learning_rate": 0.0001, "batch_size": 20},
    validation_metric=SupportedValidationMetric.ROC,

    # Configurations
    save_path_to_fine_tuned_model=PATH_TO_TUNED_MODEL,
    task_type=TaskType.BINARY_CLASSIFICATION,
    categorical_features_index=None,
    device=SupportedDevice.GPU,
    path_to_base_model="auto",
    show_training_curve=True,
    logger_level=0,
    use_wandb=True,
)
~~~

### Error I encounter if I put too much data into train set:
~~~
Fine-tuning Steps:   0%|                                                                                                 | 1/10000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/probabilistic_conflict_modelling_private/tuning_and_running/tune_tabpfn.py", line 123, in <module>
    fine_tune_tabpfn(
  File "/workspace/probabilistic_conflict_modelling_private/finetuning_scripts/finetune_tabpfn_main.py", line 291, in fine_tune_tabpfn
    step_results = _fine_tune_step(
  File "/workspace/probabilistic_conflict_modelling_private/finetuning_scripts/finetune_tabpfn_main.py", line 552, in _fine_tune_step
    scaler.scale(loss).backward()
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1125, in unpack_hook
    frame.recompute_fn(*args)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1519, in recompute_fn
    fn(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/layer.py", line 449, in forward
    state = sublayer(state)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/layer.py", line 363, in attn_between_items
    new_x_train = self.self_attn_between_items(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/multi_head_attention.py", line 355, in forward
    output: torch.Tensor = self._compute(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/memory.py", line 100, in method_
    return x + method(self, x, *args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/multi_head_attention.py", line 513, in _compute
    return torch.einsum(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/functional.py", line 402, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 752.00 MiB. GPU 0 has a total capacity of 23.53 GiB of which 128.50 MiB is free. Process 1664597 has 23.39 GiB memory in use. Of the allocated memory 22.32 GiB is allocated by PyTorch, and 630.50 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/workspace/probabilistic_conflict_modelling_private/tuning_and_running/tune_tabpfn.py", line 123, in <module>
    fine_tune_tabpfn(
  File "/workspace/probabilistic_conflict_modelling_private/finetuning_scripts/finetune_tabpfn_main.py", line 291, in fine_tune_tabpfn
    step_results = _fine_tune_step(
  File "/workspace/probabilistic_conflict_modelling_private/finetuning_scripts/finetune_tabpfn_main.py", line 552, in _fine_tune_step
    scaler.scale(loss).backward()
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1125, in unpack_hook
    frame.recompute_fn(*args)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1519, in recompute_fn
    fn(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/layer.py", line 449, in forward
    state = sublayer(state)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/layer.py", line 363, in attn_between_items
    new_x_train = self.self_attn_between_items(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/multi_head_attention.py", line 355, in forward
    output: torch.Tensor = self._compute(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/memory.py", line 100, in method_
    return x + method(self, x, *args, **kwargs)
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/tabpfn/model/multi_head_attention.py", line 513, in _compute
    return torch.einsum(
  File "/workspace/probabilistic_conflict_modelling_private/.venv/lib/python3.10/site-packages/torch/functional.py", line 402, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 752.00 MiB. GPU 0 has a total capacity of 23.53 GiB of which 128.50 MiB is free. Process 1664597 has 23.39 GiB memory in use. Of the allocated memory 22.32 GiB is allocated by PyTorch, and 630.50 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
~~~

**Comment by iivalchev** [comment]
perhaps this could work: https://github.com/LennartPurucker/finetune_tabpfn_v2/pull/11

can't really test this now, but you could give it a try

**Comment by yehorkhod** [comment]
Thanks! I'll give it a try)

**Comment by yehorkhod** [comment]
Got things working with a minor adjustment)
Check my comment at https://github.com/LennartPurucker/finetune_tabpfn_v2/pull/11

**Comment by yehorkhod** [comment]
Just checked the possibility to load tuned model, and expirienced some troubles.
~~~py
model = TabPFNClassifier(
    model_path=PATH_TO_TUNED_MODEL, ignore_pretraining_limits=True
).fit(X_train, y_train)
~~~
Error:

![Image](https://github.com/user-attachments/assets/8d745cd1-8141-4f12-8d21-e41098140245)

![Image](https://github.com/user-attachments/assets/2503ad22-9872-41f6-b946-dc64d65b6300)

![Image](https://github.com/user-attachments/assets/3c5669d4-1667-463a-9d2d-9dc9ce5a585f)

![Image](https://github.com/user-attachments/assets/6b74f857-2ae2-46bc-96f8-8ef33e95cfae)

![Image](https://github.com/user-attachments/assets/a4ce6995-b3ad-42b8-82f9-cfbc4d5dd4be)

![Image](https://github.com/user-attachments/assets/47e24450-f0c4-46f9-85c2-bb51f75f8a63)

**Comment by iivalchev** [comment]
Looks like the model is not being saved correctly. Maybe this could help: https://github.com/LennartPurucker/finetune_tabpfn_v2/pull/11

**Comment by iivalchev** [comment]
However you would need to run the fine-tuning again

**Comment by yehorkhod** [comment]
Seems to work now! Thank you very much)

**Comment by iivalchev** [comment]
@LennartPurucker this can be closed I believe

**Comment by LennartPurucker** [comment]
Great work @iivalchev, thank you for taking care of this. Feel free to ping me sooner in the future if I do not reply. 

@yehorkhod I will close the issue now. In case you get insights into how much data parallel speeds up the fine-tuning, I would love to hear them. E.g., is there a linear time increase in the number of GPUs?
